# Generated by Django 4.1.4 on 2024-03-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBoard', '0005_rename_postcategory_subscriptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
